Create userlog
sahlet-official/userlog pull request #52
Opened 2023-03-17 11:43 UTC by Yura-0

#49 Create main features

2023-03-20 11:10 UTC, sahlet-official requested changes

2023-03-20 11:10 UTC, sahlet-official commented on Sources/Userlog/user_log/lib/features/about_screen_feature/about_screen.dart
> +import 'package:flutter/material.dart';
Make folder structures inside features

2023-03-20 11:10 UTC, sahlet-official commented on Sources/Userlog/user_log/lib/features/about_screen_feature/about_screen.dart
> +import 'package:user_log/core/assets.dart';
Search for examples of how to use
Injectable
get_it
BLOC

And use in our project

2023-03-20 11:10 UTC, sahlet-official commented on Sources/Userlog/user_log/lib/features/about_screen_feature/about_screen.dart
> +
Make api folder in features where it needed

2023-04-03 14:43 UTC, sahlet-official requested changes

2023-04-03 14:43 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/features/about_screen_feature/assets/about_images.dart
> +abstract class AboutImages {
Rename features without "screen" and "feature" words

2023-04-03 14:43 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/features/about_screen_feature/assets/about_screen_texts.dart
> +abstract class AboutTexts {
remove the word screen from the name of the file. The name of file has to correspond to the name of the class

2023-04-03 14:43 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/features/about_screen_feature/screens/about_screen.dart
> +import 'package:userlog/common/styles/fonts.dart';
Make spaces between categories of imports

2023-04-03 14:43 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/features/main_screen_feature/screens/main_screen.dart
> +                      '/About',
That is why we need to make api folder in every feature.
This route has to be exported from about feature as api

2023-04-06 17:43 UTC, sahlet-official requested changes

2023-04-06 17:43 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/features/about/api/about_feature.dart
> +class AboutApi extends FeatureApi {
Lets rename AboutApi to AboutFeature

2023-04-06 17:43 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/features/main/api/main_feature.dart
> +class MainApi extends FeatureApi {
Let's rename MainApi to MainFeature

2023-04-06 17:43 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/main.dart
> +      routes.addAll(e.getRoutes());
Will "addAll" throw an exception if there will be a repeated route?

2023-04-06 17:43 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/main.dart
> +      initialRoute: '/',
replace '/' to MainRoutes.root

2023-04-06 17:43 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/main.dart
> +      routes.addAll(e.getRoutes());
call these functions (addAll and getRoutes) in different lines.

As easier code - as better

2023-04-06 17:43 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/main.dart
> +    List<FeatureApi> featuresApi = [MainApi(), AboutApi()];
write features names classes in different lines (make in as column)

2023-04-07 10:47 UTC, Yura-0 commented on Sources/Userlog/userlog/lib/main.dart
> +      routes.addAll(e.getRoutes());
No

2023-04-07 10:49 UTC, Yura-0 commented on Sources/Userlog/userlog/lib/main.dart
> +      routes.addAll(e.getRoutes());
To do this, I would need to store the value of e.getRoutes into a variable, which would force the creation of that variable, which would make the operation more complicated. Or do you have something else requesting this change

2023-04-11 16:27 UTC, sahlet-official requested changes

2023-04-11 16:27 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/main.dart
> +    List<UiFeature> featuresApi = [MainFeature(), AboutFeature()];
write it like that:
........... = [
MainFeature,
AboutFeature,
]

2023-04-11 16:27 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/main.dart
> +    List<UiFeature> featuresApi = [MainFeature(), AboutFeature()];
rename featuresApi to features

2023-04-11 17:21 UTC, Yura-0 commented on Sources/Userlog/userlog/lib/main.dart
> +    List<UiFeature> featuresApi = [MainFeature(), AboutFeature()];
I did that, but when I auto-formatted the code, it reverted the array to that look again

2023-04-11 18:01 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/main.dart
> +    List<UiFeature> featuresApi = [MainFeature(), AboutFeature()];
@Yura-0 
Ok, leave like that

2023-04-14 18:03 UTC, sahlet-official requested changes

2023-04-14 18:03 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/main.dart
> +  Map<String, WidgetBuilder> _isSameRoute(
It is a very redundant code.

make a function that gets features as parameter and returns routes

2023-04-18 14:09 UTC, sahlet-official requested changes

2023-04-18 14:09 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/main.dart
> +      route = e.getRoutes();
change it to
Map<String, WidgetBuilder> featureRoutes = e.getRoutes();

2023-04-18 14:09 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/main.dart
> +        routes.addAll(route);
this line should be out of this cycle.

2023-04-19 14:01 UTC, sahlet-official submitted a review, later dismissed

2023-04-20 12:25 UTC, sahlet-official commented
Аппрув

2023-04-21 10:12 UTC, merged