Use DI Get_it
sahlet-official/userlog pull request #65
Opened 2023-05-10 14:47 UTC by Yura-0

Resolve #58

2023-05-11 15:52 UTC, sahlet-official requested changes

2023-05-11 15:52 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/injection.config.dart
> +// GENERATED CODE - DO NOT MODIFY BY HAND
What do you think, maybe it is better to note this file in gitignore?

2023-05-11 15:52 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/services/log/services/log_service.dart
> +@singleton
If it is possible, dont mark this clas as singleton here

2023-05-11 15:58 UTC, Yura-0 commented on Sources/Userlog/userlog/lib/injection.config.dart
> +// GENERATED CODE - DO NOT MODIFY BY HAND
Okay, but I must add a new recommendation in userlog README file, where I explain how to generate dependencies

2023-05-15 11:22 UTC, sahlet-official requested changes

2023-05-15 11:22 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/injection.config.dart
> +// GENERATED CODE - DO NOT MODIFY BY HAND
It is still not hidden

2023-05-15 11:22 UTC, sahlet-official commented on Sources/Userlog/userlog/lib/services/log/dependencies/log_service_module.dart
> +abstract class LogServiceModule {
Renae it to LogServiceDiModule

2023-05-15 11:22 UTC, sahlet-official commented on Sources/Userlog/userlog/scripts/build.dart
> +// Generate file injection.confic.dart in lib folder and start build in debug mode
it has to be scripts in yaml file

like here https://flutterawesome.com/define-and-use-scripts-from-your-pubspec-yaml-file/

2023-05-15 15:56 UTC, sahlet-official requested changes

2023-05-16 12:39 UTC, sahlet-official requested changes

2023-05-16 12:39 UTC, sahlet-official commented on Sources/Userlog/userlog/scripts/build.dart
> +  if (processResult.exitCode == 0) {
we dont need this code at all, we only need ti run the script. all other will be printed on the screen

2023-05-18 20:09 UTC, merged